### ISSUE TITLE
Time complexity of your solution to Integer to Roman

### ISSUE THREAD

**Issue by DaiYue** [soapyigu/LeetCode_Swift#188]
Great solution! Although I think the time complexity is more like O(lgn), as n being num? 
Not that important anyways, since num is guaranteed to be <= 3999.

**Comment by soapyigu** [comment]
Thank you for your comment. My point there is that n represents the length of the roman number array, I should be more clear about that.

**Comment by DaiYue** [comment]
I see. Thank you for the explanation.
