### ISSUE TITLE
Link to problem #22 's solution is incorrect

### ISSUE THREAD

**Issue by DaiYue** [soapyigu/LeetCode_Swift#200]
The link to solution in README.md is off. Currently it's `https://github.com/soapyigu/LeetCode_Swift/blob/master/Math/GenerateParentheses.swift`, seems that it should be `https://github.com/soapyigu/LeetCode_Swift/blob/master/DP/GenerateParentheses.swift` instead.

**Comment by soapyigu** [comment]
Ah, I see, nice catch, fixed.
