### ISSUE TITLE
File and folder structure

### ISSUE THREAD

**Issue by bornsky** [soapyigu/LeetCode_Swift#201]
When I cloned this project I had to individually select each playground file to view the implementation. I took all your LeetCode_Swift .swift files and neatly put them in one Xcode project folder so it will be easier for anyone cloning it to have it in one place. I also added .playground files to each one. Is that something thats you are willing to consider pulling?

**Comment by soapyigu** [comment]
Sorry for the delay response, that is a good idea. Why don't you try to send a pull request so that we can discuss about it?

**Comment by bornsky** [comment]
Just submitted a pull request

**Comment by soapyigu** [comment]
Hi currently i am on vacation, will look at it when I am back. Thank you for your advice.
