### ISSUE TITLE
README for explanation 

### ISSUE THREAD

**Issue by bornsky** [soapyigu/LeetCode_Swift#212]
I think it would be cool if there was an option for each contributor to be able to explain in a REAME file their thought process and how they came up with their solutions. I think it would help people understand someone else's logic. It will also help it read better on github. I can add additional changes to the Architect branch. What do you think?

**Comment by soapyigu** [comment]
Good idea, just try that and push it to architect branch, I will take a look at it very soon.

**Comment by soapyigu** [comment]
This is already fixed.
