### ISSUE TITLE
Number of Islands complexity

### ISSUE THREAD

**Issue by stepanhruda** [soapyigu/LeetCode_Swift#85]
Currently complexity: O((n^2)!)

1. Tiles are switched to 0 once visited, so they cannot be visited again. Although the search can look into 4 directions for each tile, it doesn't keep going.
1. The instructions don't say that the board is a square (although it is in the example).

Suggested complexity: O(mn)

**Comment by soapyigu** [comment]
Hi,

For 1, I did it to track if a tile is visited or not, and that is necessary for DFS;
For 2, you are right, O(mn) is more accurate.

Thank you for your suggestions,
Yi

**Comment by stepanhruda** [comment]
Oh I agree with the approach, just meant to back up why I thought the complexity was lower. I see you already merged a fix.
