### ISSUE TITLE
Array -> ContainsDuplicate.swift

### ISSUE THREAD

**Issue by phpmaple** [soapyigu/LeetCode_Swift#90]
simple problem:
```
class Solution {
	func containsDuplicate(nums: [Int]) -> Bool {
		return nums.count > Set(nums).count
	}
}

```

**Comment by soapyigu** [comment]
Awesome solution, thank you

**Comment by stepanhruda** [comment]
You have to convert the entire array to the set. If you iterate one by one, you can bail out earlier once you detect the first duplicate.

**Comment by soapyigu** [comment]
Both solutions have the same complexity, I perfer phpmaple's as it is more concise.
